# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}

  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Background Image, name: background_image, widget: image, required: false}
          - {label: Content Logo, name: content_logo, widget: image, required: false}
          - {label: Title, name: title, widget: string, required: false}
          - {label: Content, name: content, widget: markdown, required: false}
          - {label: Logo Content, name: logo_content, widget: text, required: false}
          - {label: Logo, name: logo, widget: image, required: false}
          - {label: Suppliers Content, name: suppliers_content, widget: text, required: false}
          - {label: Suppliers, name: suppliers_logo, widget: image, required: false}
          - label: List items
            name: list_items
            widget: object
            fields:
              - {label: List Item 1, name: list_item_1, widget: text, required: false}
              - {label: List Item 2, name: list_item_2, widget: text, required: false}
              - {label: List Item 3, name: list_item_3, widget: text, required: false}
              - {label: List Item 4, name: list_item_4, widget: text, required: false}
              - {label: List Item 5, name: list_item_5, widget: text, required: false}
              - {label: List Item 6, name: list_item_6, widget: text, required: false}
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Content, name: content, widget: markdown, required: false}
          - {label: Address, name: address, widget: text, required: false}
          - {label: Phone, name: phone, widget: string, required: false}
          - {label: Fax, name: fax, widget: text, required: false}
          - {label: Email, name: email, widget: text, required: false}
      - file: "content/pages/terms.md"
        label: "Terms Page"
        name: "terms-page"
        fields:
          - {label: Content, name: content, widget: markdown, required: false}
  - name: products
    label: Product
    editor:
      preview: true
    folder: content/products
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Product Order, name: order, widget: number, required: true}
      - {label: Title, name: title, widget: string, required: false}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Dimensions, name: dimensions, widget: markdown, required: false}
      - {label: Content, name: content, widget: markdown, required: false}
      - {label: Bottom Diagram, name: bottom_diagram, widget: image, required: false}
      - {label: Bottom Diagram Excerpt, name: bottom_diagram_excerpt, widget: string, required: false}
      - {label: Bottom Full Image, name: bottom_full_image, widget: image, required: false}
      # - label: "Categories"
      #   name: "categories"
      #   widget: "list"
      #   fields:
      #     - label: "Category"
      #       name: "category"
      #       widget: "relation"
      #       collection: "postCategories"
      #       searchFields: ["title"]
      #       valueField: "title"

      - {label: Date / Order, name: date, widget: date}
      # - {label: Post Featured Image, name: postFeaturedImage, widget: image, required: false}
      # - {label: Excerpt, name: excerpt, widget: text}
      # - {label: Content, name: body, widget: markdown}
